import { type NextPage } from "next";
import Head from "next/head";
import { useUser } from "@clerk/nextjs";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data } = api.posts.getAll.useQuery();

  // console.log("Posts data ", data);
  const { user } = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center ">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <div className="flex flex-col items-center gap-2">
            <div>{`Hi, ${user?.fullName}`}</div>
          </div>
          <div>
            <p className="font-bold">Your Posts</p>
          </div>
          <div>
            <ul>
              {data?.map((item, index) => (
                <div className="flex">
                  <p className="pr-2 font-bold">{`${index + 1}. `}</p>
                  <li key={item?.id}>{`${item?.content}`}</li>
                </div>
              ))}
            </ul>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
